version: "3.8"
networks:
  app-tier:
    driver: bridge
services: 
    backend:
            container_name: appkison_back
            restart: always
            build: .
            image: appkinson_back
            ports:
                - "8000:8000"
            links: 
                - database
            volumes: 
                - .:/app
            environment: 
                - 'PASSWORD_DB=$MYSQL_ROOT_PASSWORD'
                - HOST_DB=database
            networks:
                - app-tier 
    database:
            container_name: database
            image: mysql:5.6
            
            restart: always
            ports: 
                - "3306:3306"
            environment: 
                - 'MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD'
                - MYSQL_USER=root
            volumes:
                - ./src/db/scripts:/docker-entrypoint-initdb.d
                - ./src/db/data:/var/lib/mysql:rw
            networks:
                - app-tier 