version: "3.8"

services: 
    backend:
            container_name: appkison_back
            restart: always
            build: .
            ports:
                - "8000:8001"
            links: 
                - database
            volumes: 
                - .:/app
            environment: 
                - 'PASSWORD_DB=$MYSQL_ROOT_PASSWORD'
    database:
            container_name: database
            image: mysql:5.6
            
            restart: always
            ports: 
                - "3307:3306"
            environment: 
                - 'MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD'
            volumes:
                - ./src/db/scripts:/docker-entrypoint-initdb.d
                - ./src/db/data:/var/lib/mysql:rw